import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import verification from "../extensions/verification/index.ts";
import { loadConfig } from "../extensions/verification/config.ts";
import { shutdownCommandRunner } from "../extensions/_shared/command-job-runner.ts";

test("tool trust is user-only, digest-bound, project-trust-aware; actions and shutdown work", async t => {
	const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), "verify-tool-")));
	const project = path.join(dir, "project"); fs.mkdirSync(path.join(project, ".pi"), { recursive: true });
	fs.writeFileSync(path.join(project, "input"), "input");
	const config = path.join(project, ".pi", "verification.json");
	fs.writeFileSync(config, JSON.stringify({ version: 1, checks: [{ id: "node", command: process.execPath, args: ["-e", ""], cwd: ".", timeoutSeconds: 2, inputs: { paths: ["input"], exclude: [], untracked: "include" }, report: { format: "exit" } }] }));
	const old = process.env.PI_COMMAND_STATE_DIR; process.env.PI_COMMAND_STATE_DIR = path.join(dir, "jobs");
	let tool: any, command: any, approved = false, flag: string | undefined;
	const events = new Map<string, any>();
	const pi = { registerTool: (t: any) => tool = t, registerCommand: (_: string, c: any) => command = c, registerFlag() {}, getFlag: () => flag, on: (name: string, fn: any) => events.set(name, fn) };
	verification(pi as any);
	const ctx = { cwd: project, hasUI: true, isProjectTrusted: () => true, ui: { confirm: async () => approved, notify() {} } };
	const updates: any[] = [];
	const call = (params: any) => tool.execute("call", params, undefined, (u: any) => updates.push(u), ctx);
	t.after(async () => { await events.get("session_shutdown")(); await shutdownCommandRunner(); if (old === undefined) delete process.env.PI_COMMAND_STATE_DIR; else process.env.PI_COMMAND_STATE_DIR = old; fs.rmSync(dir, { recursive: true, force: true }); });
	await events.get("session_start")({}, ctx);
	assert.equal(tool.executionMode, "sequential");
	assert.equal((await call({ action: "list" })).details.checks.length, 1);
	await assert.rejects(call({ action: "run", check: "node" }), /not trusted/);
	await assert.rejects(call({ action: "run", check: "node", trust: true }), /Invalid/);
	await command.handler("", ctx); await assert.rejects(call({ action: "run", check: "node" }), /not trusted/);
	approved = true; await command.handler("", ctx);
	ctx.isProjectTrusted = () => false; await assert.rejects(call({ action: "run", check: "node" }), /Trust/);
	ctx.isProjectTrusted = () => true;
	const ran = await call({ action: "run", check: "node" }); assert.equal(ran.details.verdict, "passed");
	assert.equal(updates[0].details.id, ran.details.id);
	assert.equal((await call({ action: "result", id: ran.details.id })).details.verdict, "passed");
	fs.appendFileSync(config, " "); await assert.rejects(call({ action: "run", check: "node" }), /not trusted/);
	flag = (await loadConfig(project)).sha256; await events.get("session_start")({}, ctx);
	assert.equal((await call({ action: "run", check: "node" })).details.verdict, "passed");
	await assert.rejects(call({ action: "run" }), /Invalid/);
	await assert.rejects(call({ action: "unknown" }), /Invalid/);
	await assert.rejects(call({ action: "list", id: "ignored" }), /Invalid/);
});
