"""Data-only model shortcuts for the stock Pi CLI. No shell evaluation or discovery."""
from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import re
import stat
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
COMMANDS = {"install", "remove", "uninstall", "update", "list", "config", "auth", "setup", "help", "version"}
VALUES = {"--aliases", "--models-out", "--provider-name", "--gateway-url", "--gateway-api-key",
          "--pi-agent-dir", "--omlx-status", "--omlx-status-url", "--shared-dir"}
FLAGS = {"--direct-launchers", "--no-direct-launchers", "--allow-empty-catalog"}
PATHS = {"--aliases", "--models-out", "--pi-agent-dir", "--omlx-status", "--shared-dir"}
LIMIT = 8 * 1024 * 1024


def digest(raw):
    return hashlib.sha256(raw).hexdigest()


def read_owned(path, missing=False):
    path = Path(path)
    if missing and not path.exists() and not path.is_symlink():
        return b""
    target = path.resolve(strict=True)
    info, parent = target.stat(), target.parent.stat()
    if (not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid() or info.st_mode & 0o022
            or info.st_nlink != 1 or parent.st_uid != os.getuid() or parent.st_mode & 0o022
            or info.st_size > LIMIT):
        raise ValueError(f"Unsafe or oversized launcher input: {path}")
    with target.open("rb") as stream:
        raw = stream.read(LIMIT + 1)
    if len(raw) > LIMIT:
        raise ValueError(f"Oversized launcher input: {path}")
    return raw


def atomic_write(path, content):
    target = Path(path).resolve()
    parent = target.parent
    ancestor = parent
    while not ancestor.exists():
        ancestor = ancestor.parent
    info = ancestor.stat()
    if info.st_uid != os.getuid() or info.st_mode & 0o022:
        raise ValueError(f"Unsafe output directory: {ancestor}")
    if target.exists():
        read_owned(target)
    parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    fd, name = tempfile.mkstemp(prefix=".pi-launch-", dir=parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(name, target)
    finally:
        if os.path.exists(name):
            os.unlink(name)


def dump(value):
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def generation_values(args):
    if not isinstance(args, list) or len(args) > 48 or any(
            not isinstance(a, str) or not a or "\0" in a or len(a) > 8192 for a in args):
        raise ValueError("Invalid generation arguments")
    values = {}
    i = 0
    while i < len(args):
        flag = args[i]
        if flag not in VALUES | FLAGS or flag in values:
            raise ValueError(f"Unsupported/duplicate generation option: {flag}")
        i += 1
        if flag in FLAGS:
            values[flag] = True
        else:
            if i == len(args):
                raise ValueError(f"Missing value: {flag}")
            values[flag] = args[i]
            i += 1
    if "--direct-launchers" in values and "--no-direct-launchers" in values:
        raise ValueError("Conflicting direct launcher flags")
    for key in PATHS & values.keys():
        if not Path(values[key]).is_absolute():
            raise ValueError(f"Generation path must be absolute: {key}")
    if not values.get("--aliases") or not values.get("--shared-dir"):
        raise ValueError("Missing generation identity")
    if Path(values["--shared-dir"]).resolve() != ROOT:
        raise ValueError("Launcher belongs to another shared installation; regenerate with pi-catalog")
    roles = [Path(values[k]).resolve() for k in ("--aliases", "--models-out", "--omlx-status") if k in values]
    if len(roles) != len(set(roles)):
        raise ValueError("Input/output paths overlap")
    return values


def legacy_arguments(path):
    """Import only recognized JSON metadata; never source legacy shell code."""
    text = read_owned(path).decode("utf-8")
    prefix = "# pi-catalog-args: "
    rows = [line[len(prefix):] for line in text.splitlines() if line.startswith(prefix)]
    if not text.startswith("# Generated by pi-shared/bin/pi-catalog — do not hand-edit.\n") or len(rows) != 1:
        raise ValueError("Legacy launcher lacks recognized JSON metadata; leaving it untouched")
    args = json.loads(rows[0])
    if not isinstance(args, list):
        raise ValueError("Invalid legacy arguments")
    # Legacy output is deliberately NOT rewritten or sourced.
    indices = [i for i, arg in enumerate(args) if arg == "--launchers-out"]
    if len(indices) != 1 or indices[0] + 1 >= len(args):
        raise ValueError("Missing legacy output identity")
    i = indices[0]
    if Path(args[i + 1]).resolve() != Path(path).resolve():
        raise ValueError("Legacy output identity mismatch")
    args = args[:i] + args[i + 2:]
    generation_values(args)
    return args


def legacy_metadata(path):
    """Recover the status hints and models digest a legacy launcher recorded.

    Only the recognized ``# pi-catalog-status`` / ``# pi-catalog-models-sha256``
    comment lines are read; the shell body is never evaluated. Missing lines
    fall back to empty status / unmanaged digest so migration stays lossless
    but conservative.
    """
    text = read_owned(path).decode("utf-8")
    status, models_digest = {}, "unmanaged"
    for line in text.splitlines():
        if line.startswith("# pi-catalog-status: "):
            parsed = json.loads(line[len("# pi-catalog-status: "):])
            if isinstance(parsed, dict):
                status = parsed
        elif line.startswith("# pi-catalog-models-sha256: "):
            value = line[len("# pi-catalog-models-sha256: "):].strip()
            if re.fullmatch("[a-f0-9]{64}", value) or value == "unmanaged":
                models_digest = value
    return status, models_digest


def routes_for(aliases, provider, profile, direct):
    from pi_catalog import _eligible_entries, _model_id_for, _pi_hints
    routes = {}
    for key, meta in _eligible_entries(aliases):
        for alias in [str(meta["alias"]), *(_pi_hints(meta).get("aliases") or [])]:
            if alias in COMMANDS:
                raise ValueError(f"Alias collides with stock Pi command: {alias}")
            routes[alias] = {"provider": provider, "model": _model_id_for(key, meta),
                             "profile": profile, "gateway": True}
    if direct:
        routes["openai"] = {"provider": "openai-codex", "model": "gpt-6-astra",
                            "profile": None, "gateway": False}
    return dict(sorted(routes.items()))


def make_config(aliases, args, status, models_digest, aliases_digest, default_profile=None):
    values = generation_values(args)
    routes = routes_for(aliases, values["--provider-name"], values.get("--pi-agent-dir"),
                        "--direct-launchers" in values)
    return {"version": 1, "routes": routes, "defaultProfile": default_profile,
            "generation": {"args": args, "status": status, "modelsSha256": models_digest,
                           "aliasesSha256": aliases_digest}}


def load_config(path):
    config = json.loads(read_owned(path))
    if not isinstance(config, dict) or config.get("version") != 1:
        raise ValueError("Unsupported launcher config version")
    generation = config.get("generation")
    if not isinstance(generation, dict):
        raise ValueError("Missing generation metadata")
    values = generation_values(generation.get("args"))
    for key in ("--aliases", "--models-out", "--omlx-status"):
        if key in values and Path(values[key]).resolve() == path.resolve():
            raise ValueError("Launcher input/output paths overlap")
    for key in ("modelsSha256", "aliasesSha256"):
        value = generation.get(key)
        if not isinstance(value, str) or not (re.fullmatch("[a-f0-9]{64}", value) or value == "unmanaged"):
            raise ValueError("Invalid digest metadata")
    status = generation.get("status")
    if not isinstance(status, dict) or any(not isinstance(v, dict) or
            set(v) - {"max_context_window", "max_tokens", "thinking_default"} or
            any(not isinstance(x, (bool, int, str)) for x in v.values()) for v in status.values()):
        raise ValueError("Invalid cached status")
    profile = config.get("defaultProfile")
    if profile is not None and (not isinstance(profile, str) or not Path(profile).is_absolute() or "\0" in profile):
        raise ValueError("Invalid default profile")
    routes = config.get("routes")
    if not isinstance(routes, dict):
        raise ValueError("Invalid routes")
    for alias, route in routes.items():
        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]*", alias) or alias in COMMANDS:
            raise ValueError("Invalid/reserved route alias")
        if not isinstance(route, dict) or set(route) != {"provider", "model", "profile", "gateway"}:
            raise ValueError("Invalid route")
        if any(not isinstance(route[k], str) or not route[k] or "\0" in route[k] for k in ("provider", "model")):
            raise ValueError("Invalid route model/provider")
        if type(route["gateway"]) is not bool:
            raise ValueError("Invalid route kind")
        p = route["profile"]
        if p is not None and (not isinstance(p, str) or not Path(p).is_absolute() or "\0" in p):
            raise ValueError("Invalid route profile")
    return config


def refresh(path, config, check=False):
    """Re-render both outputs in memory, protecting manual models edits before writes."""
    from pi_catalog import render_models, _dump, _load_omlx_status
    gen = config["generation"]
    values = generation_values(gen["args"])
    raw = read_owned(Path(values["--aliases"]), missing="--allow-empty-catalog" in values)
    aliases = json.loads(raw) if raw else {}
    if not isinstance(aliases, dict) or any(not isinstance(v, dict) for v in aliases.values()):
        raise ValueError("Expected an alias catalog object of model objects")
    if not aliases and ("--allow-empty-catalog" not in values or any(r["gateway"] for r in config["routes"].values())):
        raise ValueError("Refusing to erase configured routes with an empty catalog")
    status = gen["status"]
    if "--omlx-status" in values:
        read_owned(Path(values["--omlx-status"]))
        status = _load_omlx_status(Path(values["--omlx-status"]), None)
    models = Path(values["--models-out"]) if "--models-out" in values else None
    content = None
    expected = gen["modelsSha256"]
    if models:
        old = read_owned(models, missing=True)
        if old and (expected == "unmanaged" or digest(old) != expected):
            raise ValueError("Generated models were edited or unmanaged; inspect models.json before regenerating with pi-catalog")
        if aliases:
            content = _dump(render_models(aliases, provider_name=values["--provider-name"],
                            gateway_url=values["--gateway-url"], gateway_api_key=values["--gateway-api-key"],
                            omlx_status=status))
            expected = digest(content.encode())
    updated = make_config(aliases, gen["args"], status, expected, digest(raw), config.get("defaultProfile"))
    changed = updated != config or (content is not None and content.encode() != old)
    if check:
        if changed:
            raise ValueError("Launcher catalog is stale; run --launcher-refresh")
        return config
    if changed:
        # Check every output before writing either one.
        if path.exists():
            read_owned(path)
        if content is not None:
            atomic_write(models, content)
        atomic_write(path, dump(updated))
    return updated


def configure(path, overrides):
    """Apply explicitly requested installer route changes, retaining other metadata."""
    from pi_catalog import main as render
    config = refresh(path, load_config(path))  # protect any manual model edits
    values = generation_values(config["generation"]["args"])
    original_models = values.get("--models-out")
    i = 0
    while i < len(overrides):
        flag = overrides[i]
        i += 1
        if flag in {"--direct-launchers", "--no-direct-launchers"}:
            values.pop("--direct-launchers", None)
            values.pop("--no-direct-launchers", None)
            values[flag] = True
        elif flag in {"--aliases", "--models-out", "--provider-name", "--pi-agent-dir"} and i < len(overrides):
            value = overrides[i]
            i += 1
            if flag == "--pi-agent-dir" and not value:
                values.pop(flag, None)
            else:
                values[flag] = value
        else:
            raise ValueError("Unsupported installer routing override")
    args = [part for flag, value in values.items() for part in ([flag] if value is True else [flag, value])]
    generation_values(args)
    output = values.get("--models-out")
    if output and (not original_models or Path(output).resolve() != Path(original_models).resolve()) and Path(output).exists():
        raise ValueError("Refusing to adopt an existing different models output; reconcile it with pi-catalog explicitly")
    with tempfile.TemporaryDirectory(prefix="pi-cli-configure-") as directory:
        cache = Path(directory) / "status.json"
        cache.write_text(json.dumps({"models": [{"id": key, **row} for key, row in config["generation"]["status"].items()]}))
        result = render([*args, "--cli-out", str(path), "--offline", "--status-cache", str(cache), "--quiet"])
    if result:
        raise ValueError("CLI configuration rendering failed")


# Inspect only actual option tokens, not option values or literal prompts.
STOCK_VALUES = {"--provider", "--model", "--models", "--mode", "--api-key", "--thinking", "--session",
                "--fork", "--session-id", "--session-dir", "--name", "-n", "--tools", "-t", "--exclude-tools", "-xt",
                "-e", "--extension", "--skill", "--prompt-template", "--theme", "--system-prompt",
                "--append-system-prompt", "--tui-mode", "--use-theme", "--export"}


def options(argv):
    found = set()
    i = 0
    while i < len(argv):
        token = argv[i]
        if token == "--":
            break
        name = token.split("=", 1)[0]
        if name.startswith("-"):
            found.add(name)
        i += 2 if name in STOCK_VALUES and "=" not in token else 1
    return found


def upstream():
    value = os.environ.get("PI_UPSTREAM_BIN", "")
    path = Path(value)
    if not value or not path.is_absolute() or not path.is_file() or not os.access(path, os.X_OK):
        raise ValueError("PI_UPSTREAM_BIN must name the absolute stock Pi executable (provided by packaging)")
    # Packaging supplies an absolute stock executable and we exec that path
    # directly (never a PATH lookup), so a `pi` shim on PATH cannot recurse.
    # The only remaining risk is a misconfigured value pointing back at this
    # launcher; reject that explicitly. No environment guard is exported on the
    # exec, so spawned subagents/bash tools inherit no recursion guard.
    if path.resolve() == (ROOT / "bin/pi-launch").resolve():
        raise ValueError("Recursive Pi launcher target")
    return str(path)


def main(argv=None):
    # pi-launch receives ORDINARY Pi argv with NO extra transport separator
    # (packaging invokes `pi-launch <user argv...>` directly). A user's
    # `pi -- <literal>` therefore arrives here as `-- <literal>` and is passed
    # through to the stock CLI verbatim, so aliases never intercept it.
    argv = list(sys.argv[1:] if argv is None else argv)
    path = Path(os.environ.get("PI_LAUNCHER_CONFIG", "~/.pi/launcher.json")).expanduser().absolute()
    try:
        if argv == ["--launcher-help"]:
            print("pi <exact-alias> [Pi options] | pi <alias> --default (save and exit)\n"
                  "pi openai: ChatGPT subscription preset (when direct routes enabled)\n"
                  "--launcher-list | --launcher-check | --launcher-refresh | --launcher-help\n"
                  "--launcher-migrate <legacy pi-launchers.zsh> (offline, one-time bootstrap)\n"
                  "pi -- <literal prompt> bypasses aliases; pi list remains the stock package command.")
            return 0
        if argv[:1] == ["--launcher-migrate"]:
            # Offline one-time bootstrap: reconstruct the CLI config from a
            # legacy zsh launcher's recognized JSON metadata (source, provider,
            # profile, endpoint, direct opt-out) WITHOUT evaluating shell, and
            # without requiring PI_UPSTREAM_BIN. Never clobber an existing config.
            if len(argv) != 2:
                raise ValueError("--launcher-migrate takes exactly one legacy launcher path")
            if path.exists():
                raise ValueError(f"Refusing to overwrite an existing launcher config: {path}")
            legacy = Path(argv[1]).expanduser().absolute()
            args = legacy_arguments(legacy)
            status, models_digest = legacy_metadata(legacy)
            values = generation_values(args)
            raw = read_owned(Path(values["--aliases"]), missing="--allow-empty-catalog" in values)
            aliases = json.loads(raw) if raw else {}
            if not isinstance(aliases, dict) or any(not isinstance(v, dict) for v in aliases.values()):
                raise ValueError("Expected an alias catalog object of model objects")
            config = make_config(aliases, args, status, models_digest, digest(raw))
            atomic_write(path, dump(config))
            print(f"Migrated legacy launcher into {path} ({len(config['routes'])} routes).", file=sys.stderr)
            return 0
        if argv in (["--launcher-list"], ["--launcher-check"], ["--launcher-refresh"]):
            # --launcher-check is a read-only doctor helper: it must succeed
            # without PI_UPSTREAM_BIN (doctor calls it directly, off the exec
            # path). --launcher-refresh is explicit and offline; neither runs
            # inference or touches the stock executable. A required config must
            # exist: doctors must never report success for missing routing.
            if not path.exists():
                raise ValueError("Pi launcher CLI mode not configured; run pi-shared setup")
            config = load_config(path)
            config = refresh(path, config, check=argv == ["--launcher-check"])
            if argv == ["--launcher-list"]:
                for alias, route in config["routes"].items():
                    print(f"{alias}\t{route['provider']}/{route['model']}")
            else:
                print("Pi launcher configuration OK (offline; no inference).")
            return 0
        executable = upstream()
        env = dict(os.environ)
        opts = options(argv)
        utility = bool(argv and argv[0] in COMMANDS) or bool(opts & {"--help", "-h", "--version", "-v", "--export", "--list-models"})
        explicit_model = bool(opts & {"--provider", "--model"})
        config = None
        route = None
        # Utilities and literal prompts must work even if launcher metadata is broken.
        literal = argv[:1] == ["--"]
        if not utility and not literal and path.exists():
            config = load_config(path)
            if argv and not argv[0].startswith("-"):
                # Refresh first to discover newly added shortcuts and retire removed ones.
                config = refresh(path, config)
                route = config["routes"].get(argv[0])
        save = route is not None and argv[1:] == ["--default"]
        if route:
            argv.pop(0)
            if "--default" in options(argv) and not save:
                raise ValueError("--default must be used alone after an exact alias")
            if explicit_model:
                route = None  # Explicit stock selection wins, with no implicit profile switch.
        if route:
            profile = env.get("PI_CODING_AGENT_DIR", route["profile"] or str(Path.home() / ".pi/agent"))
            if "PI_CODING_AGENT_DIR" not in env and route["profile"]:
                env["PI_CODING_AGENT_DIR"] = profile
            if save:
                settings_path = Path(profile).expanduser() / "settings.json"
                raw = read_owned(settings_path, missing=True)
                settings = json.loads(raw) if raw else {}
                if not isinstance(settings, dict):
                    raise ValueError("Expected settings object")
                settings.update(defaultProvider=route["provider"], defaultModel=route["model"])
                atomic_write(settings_path, dump(settings))
                # Explicit profiles never change the profile of future unqualified invocations.
                if "PI_CODING_AGENT_DIR" not in os.environ:
                    config["defaultProfile"] = route["profile"]
                    atomic_write(path, dump(config))
                print(f"Saved Pi default: {route['provider']}/{route['model']}", file=sys.stderr)
                return 0
            argv = ["--provider", route["provider"], "--model", route["model"], *argv]
            if not route["gateway"]:
                for key in ("OPENAI_API_KEY", "OPENAI_BASE_URL"):
                    env.pop(key, None)
        elif config and not explicit_model and not opts & {"--resume", "-r", "--continue", "-c", "--session", "--fork"}:
            if "PI_CODING_AGENT_DIR" not in env and config.get("defaultProfile"):
                env["PI_CODING_AGENT_DIR"] = config["defaultProfile"]
        # Repair only the configured gateway profile, not arbitrary caller profiles.
        if not utility and not explicit_model and config:
            values = generation_values(config["generation"]["args"])
            gateway_profile = values.get("--pi-agent-dir") or str(Path.home() / ".pi/agent")
            active_profile = env.get("PI_CODING_AGENT_DIR", str(Path.home() / ".pi/agent"))
            if active_profile == gateway_profile and (route and route["gateway"] or config.get("defaultProfile") == active_profile):
                config = refresh(path, config)
                repair_env = dict(env, PI_OMLX_AGENT_DIR=active_profile, PI_SHARED_DIR=str(ROOT))
                result = subprocess.run([str(ROOT / "bin/pi-omlx-repair")], env=repair_env, stdout=sys.stderr)
                if result.returncode:
                    return result.returncode
        os.execve(executable, [executable, *argv], env)
    except (OSError, ValueError, TypeError, KeyError) as exc:
        print(f"pi-launch: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
